const PROGRAMS=[
 {s:0,e:300,name:'Prabhat — Zubeen Morning',as:'প্ৰভাত — জুবিন মৰ্ণিং',desc:'Soft Assamese mornings, borgeet, lokogeet and devotional favourites.'},
 {s:300,e:540,name:'Bihu Beats',as:'বিহু বিটছ',desc:'Pepa, dhol and high-energy songs to lift the day.'},
 {s:540,e:1020,name:'Zubeen Classics',as:'জুবিন ক্লাছিকছ',desc:'The songs that shaped generations of listeners.'},
 {s:1020,e:1320,name:'Evening Memories',as:'সন্ধিয়াৰ স্মৃতি',desc:'Warm Assamese and Hindi favourites for the evening.'},
 {s:1320,e:1440,name:'Midnight Zubeen',as:'মাজনিশাৰ জুবিন',desc:'Slow, soulful melodies through the night.'}
];
let songs=[],current=null,player=null,playerReady=false,playing=false,localPaused=false,ytApiFailed=false,stationState=null,stationPoll=null,progressTimer=null,serverClockOffsetMs=0,nativeAudio=null,nativeAudioReady=false;
const RADIO_SYNC_MS=1500,RADIO_DRIFT_SEC=.75,session=localStorage.getItem('zubeen_sid')||crypto.randomUUID();
localStorage.setItem('zubeen_sid',session);const $=id=>document.getElementById(id);
function now(){const d=new Date(),m=d.getHours()*60+d.getMinutes();return{d,m,p:PROGRAMS.find(x=>m>=x.s&&m<x.e)||PROGRAMS[4]};}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function fmt(sec){sec=Math.max(0,Math.floor(Number(sec)||0));return`${Math.floor(sec/60)}:${String(sec%60).padStart(2,'0')}`}
function programClock(p){const start=`${String(Math.floor(p.s/60)).padStart(2,'0')}:00`;const end=p.e===1440?'00:00':`${String(Math.floor(p.e/60)).padStart(2,'0')}:00`;return`${start}–${end}`}
function updateProgress(){try{let t=0,d=Number(stationState?.duration||0);if(nativeAudioReady&&nativeAudio){t=Number(nativeAudio.currentTime||0);d=Number(nativeAudio.duration||d);}else if(playerReady&&player&&typeof player.getCurrentTime==='function'){t=Number(player.getCurrentTime()||0);d=Number(player.getDuration()||d);}else if(stationState){t=stationPosition(stationState);d=Number(stationState.duration||current?.duration||0)}$('cur').textContent=fmt(t);$('dur').textContent=fmt(d);if(d>0){$('seek').max=String(d);$('seek').value=String(Math.min(t,d));}}catch{}}
function startProgress(){clearInterval(progressTimer);progressTimer=setInterval(updateProgress,200);updateProgress()}
function notice(t,ok=false){$('notice').textContent=t;$('notice').className='notice '+(ok?'ok':'')}
function tick(){const x=now(),d=x.d,clock=d.toLocaleTimeString('en-IN',{hour:'numeric',minute:'2-digit'}),date=d.toLocaleDateString('en-IN',{weekday:'long',day:'2-digit',month:'long',year:'numeric'});$('clock').textContent=clock;$('date').textContent=`${date} · IST`;$('bigClock').textContent=clock;$('bigDate').textContent=date;$('tuneClock').textContent=clock;$('tuneDate').textContent=`${date} · IST`;const left=Math.max(0,x.p.e-x.m);$('programName').textContent=x.p.name.toUpperCase();$('currentShow').textContent=x.p.name;$('tuneProgram').textContent=x.p.name.toUpperCase();$('programRemain').textContent=`${left} MIN LEFT`;const next=PROGRAMS[(PROGRAMS.indexOf(x.p)+1)%PROGRAMS.length];$('nextShow').textContent=next.name;renderSchedule(x.p)}
function renderSchedule(){/* schedule is available on schedule.html; home page intentionally keeps the clean 4.3 layout */}
async function bootstrap(){const category=now().p.name;notice('Automatic song search running…');try{const r=await fetch('/api/radio/bootstrap',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({category,legacyCategory:category})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Radio server error');songs=(d.items||[]).filter(s=>s.youtubeId||s.audioUrl);if(!songs.length)throw new Error('No playable songs returned');notice(d.api?'YouTube automatic discovery active.':'Radio ready — fallback catalogue active.',true)}catch(e){notice(e.message||'Radio load failed')}}
function showDirectEmbed(id,autoplay=false,startSeconds=0){const box=$('yt');if(!id){box.innerHTML='';return}const src=`https://www.youtube.com/embed/${encodeURIComponent(id)}?autoplay=${autoplay?1:0}&start=${Math.floor(Math.max(0,startSeconds))}&controls=0&enablejsapi=1&rel=0&playsinline=1&modestbranding=1&origin=${encodeURIComponent(location.origin)}`;box.innerHTML=`<iframe id="ytDirect" title="Zubeen Radio YouTube Player" src="${src}" allow="autoplay; encrypted-media; picture-in-picture" allowfullscreen></iframe>`;playerReady=false;playing=autoplay;localPaused=false;setPlayLabel()}
function setMediaSession(song){try{if(!('mediaSession' in navigator))return;navigator.mediaSession.metadata=new MediaMetadata({title:song?.title||'Zubeen Radio',artist:song?.artist||'Zubeen Garg',album:'Zubeen Radio',artwork:song?.thumbnail?[{src:song.thumbnail,sizes:'512x512',type:'image/jpeg'}]:[]});navigator.mediaSession.setActionHandler('play',()=>resumeLocal());navigator.mediaSession.setActionHandler('pause',()=>pauseLocal());navigator.mediaSession.setActionHandler('seekbackward',e=>seekNative(-(e.seekOffset||10)));navigator.mediaSession.setActionHandler('seekforward',e=>seekNative(e.seekOffset||10));}catch{}}
function seekNative(delta){if(nativeAudioReady&&nativeAudio){nativeAudio.currentTime=Math.max(0,Math.min(nativeAudio.duration||Infinity,nativeAudio.currentTime+delta));updateProgress();}}
function setupNativeAudio(){nativeAudio=$('radioAudio');if(!nativeAudio)return;nativeAudio.addEventListener('playing',()=>{nativeAudioReady=true;playing=true;$('wave').classList.add('live');setPlayLabel();try{navigator.mediaSession.playbackState='playing'}catch{}});nativeAudio.addEventListener('pause',()=>{playing=false;$('wave').classList.remove('live');setPlayLabel();try{navigator.mediaSession.playbackState='paused'}catch{}});nativeAudio.addEventListener('ended',()=>{playing=false;localPaused=false;setPlayLabel();setTimeout(()=>syncStation(true),300)});nativeAudio.addEventListener('loadedmetadata',()=>{nativeAudioReady=true;try{navigator.mediaSession.setPositionState?.({duration:nativeAudio.duration,playbackRate:nativeAudio.playbackRate,position:Math.min(nativeAudio.currentTime,nativeAudio.duration)})}catch{}})}
function playNative(song,position,autoPlay){if(!nativeAudio)return false;nativeAudioReady=false;nativeAudio.src=song.audioUrl;nativeAudio.currentTime=Math.max(0,Number(position)||0);setMediaSession(song);if(autoPlay)nativeAudio.play().catch(()=>{notice('Tap TUNE IN again to allow audio playback.');});return true;}
function applySong(song,position=0,autoPlay=false){if(!song)return;current=song;$('title').textContent=current.title;$('artist').textContent=current.artist||'Zubeen Garg';$('meta').textContent=`${current.year||'—'} • ${current.audioUrl?'Direct audio stream':current.source==='youtube-api'?'YouTube API':'YouTube'} • GLOBAL RADIO`;$('cover').style.backgroundImage=current.thumbnail?`url("${current.thumbnail}")`:'';$('cover').classList.toggle('has',!!current.thumbnail);$('cover').textContent=current.thumbnail?'':'ZG';const target=Math.max(0,Number(position)||0);if(current.audioUrl){if(playerReady&&player&&typeof player.stopVideo==='function'){try{player.stopVideo()}catch{}};if(playNative(current,target,autoPlay))return;}if(playerReady&&player&&current.youtubeId){player.loadVideoById({videoId:current.youtubeId,startSeconds:target});autoPlay?player.playVideo():player.pauseVideo();setMediaSession(current);return}if(ytApiFailed||!window.YT)showDirectEmbed(current.youtubeId,autoPlay,target);setMediaSession(current)}
function stationPosition(st){if(!st)return 0;if(st.startedAt)return Math.max(0,(Date.now()+serverClockOffsetMs-Number(st.startedAt))/1000);return Math.max(0,Number(st.position)||0)}
function applyStationState(st,autoPlay=false){if(!st?.song)return;if(st.serverNow)serverClockOffsetMs=Number(st.serverNow)-Date.now();const target=stationPosition(st),same=current?.id===st.song.id;stationState=st;if(!same){applySong(st.song,target,autoPlay);return}if(nativeAudioReady&&nativeAudio){try{if(Math.abs(Number(nativeAudio.currentTime||0)-target)>RADIO_DRIFT_SEC)nativeAudio.currentTime=target;if(autoPlay&&!localPaused)nativeAudio.play().catch(()=>{});}catch{}}else if(playerReady&&player&&typeof player.getCurrentTime==='function'){try{const cur=Number(player.getCurrentTime()||0);if(Math.abs(cur-target)>RADIO_DRIFT_SEC)player.seekTo(target,true)}catch{}}else{const frame=document.getElementById('ytDirect');if(frame)try{frame.contentWindow.postMessage(JSON.stringify({event:'command',func:'seekTo',args:[target,true]}),'https://www.youtube.com')}catch{}}if(autoPlay&&!nativeAudioReady){if(playerReady&&player)player.playVideo();else{const frame=document.getElementById('ytDirect');if(frame)try{frame.contentWindow.postMessage(JSON.stringify({event:'command',func:'playVideo',args:[]}),'https://www.youtube.com')}catch{}}}}
async function syncStation(autoPlay=false){const category=now().p.name;try{const r=await fetch('/api/radio/state?category='+encodeURIComponent(category),{cache:'no-store'}),st=await r.json();if(!r.ok)throw new Error(st.error||'Station state unavailable');applyStationState(st,autoPlay)}catch(e){if(!stationState&&songs[0])applySong(songs[0],0,autoPlay)}}
function startStationSync(){clearInterval(stationPoll);stationPoll=setInterval(()=>syncStation(false),RADIO_SYNC_MS)}
async function syncAndPlay(){try{const category=now().p.name,r=await fetch('/api/radio/state?category='+encodeURIComponent(category),{cache:'no-store'}),st=await r.json();if(!r.ok)throw new Error(st.error||'Station unavailable');applyStationState(st,true);notice('Live radio • synchronized with the station.',true);$('tune').classList.add('hide')}catch{notice('Radio connection unavailable. Please try again.')}}
async function reportDuration(duration){if(!current?.id||!duration)return;try{const r=await fetch('/api/radio/report-duration',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({category:now().p.name,songId:current.id,duration})});const st=await r.json();if(r.ok&&st.song){stationState=st;updateProgress()}}catch{}}
async function loadHistory(){/* history panel removed from home page */}

function onYTReady(){try{player=new YT.Player('yt',{width:'100%',height:'100%',videoId:'',playerVars:{controls:0,rel:0,playsinline:1,origin:location.origin},events:{onReady:()=>{playerReady=true;startProgress();if(current?.youtubeId)player.cueVideoById({videoId:current.youtubeId,startSeconds:stationPosition(stationState)});try{const d=player.getDuration();if(d>0)reportDuration(d)}catch{}},onStateChange:e=>{if(e.data===YT.PlayerState.PLAYING){playing=true;if(!localPaused)setPlayLabel();$('wave').classList.add('live');try{if(player.getDuration()>0)reportDuration(player.getDuration())}catch{}}else if(e.data===YT.PlayerState.PAUSED||e.data===YT.PlayerState.CUED){playing=false;if(!localPaused)setPlayLabel();$('wave').classList.remove('live')}else if(e.data===YT.PlayerState.ENDED){playing=false;localPaused=false;setPlayLabel();setTimeout(()=>syncStation(true),500)}},onError:e=>{playing=false;localPaused=false;setPlayLabel();notice(`This YouTube video cannot play (error ${e.data}). Station remains synchronized.`);setTimeout(()=>syncStation(true),1000)}}})}catch{ytApiFailed=true;if(current?.youtubeId)showDirectEmbed(current.youtubeId,false)}}
window.onYouTubeIframeAPIReady=onYTReady;function loadYTApi(){if(window.YT?.Player){onYTReady();return}const s=document.createElement('script');s.src='https://www.youtube.com/iframe_api';s.async=true;s.onerror=()=>{ytApiFailed=true;if(current?.youtubeId)showDirectEmbed(current.youtubeId,false);notice('YouTube API unavailable. Direct embed enabled.',true)};document.head.appendChild(s);setTimeout(()=>{if(!playerReady&&!window.YT?.Player){ytApiFailed=true;if(current?.youtubeId)showDirectEmbed(current.youtubeId,false);notice('YouTube API unavailable. Direct embed enabled.',true)}},7000)}
$('tuneBtn').onclick=syncAndPlay;
function setPlayLabel(){ $('play').textContent=localPaused?'▶ RESUME':(playing?'❚❚ PAUSE':'▶ TUNE IN'); }
function sendYTCommand(func,args=[]){const frame=document.getElementById('ytDirect');if(frame)try{frame.contentWindow.postMessage(JSON.stringify({event:'command',func,args}),'https://www.youtube.com')}catch{} }
function pauseLocal(){
  localPaused=true; playing=false;
  if(nativeAudioReady&&nativeAudio){try{nativeAudio.pause()}catch{}}
  else if(playerReady&&player&&typeof player.pauseVideo==='function'){try{player.pauseVideo()}catch{}}
  else sendYTCommand('pauseVideo');
  $('wave').classList.remove('live'); setPlayLabel(); notice('Paused for this listener • station continues live for everyone else.',true);
}
function resumeLocal(){
  localPaused=false;
  if(nativeAudioReady&&nativeAudio){nativeAudio.play().catch(()=>notice('Tap the player once to resume audio.'))}
  else if(playerReady&&player&&typeof player.playVideo==='function'){try{player.playVideo()}catch{}}
  else sendYTCommand('playVideo');
  playing=true; $('wave').classList.add('live'); setPlayLabel(); notice('Resumed • your playback continues from where you paused.',true);
}
$('play').onclick=()=>{
  if(localPaused){resumeLocal();return;}
  if(playing){pauseLocal();return;}
  syncAndPlay();
};
$('bgBtn').onclick=()=>document.body.classList.toggle('no-bg');$('screenBtn').onclick=()=>document.documentElement.requestFullscreen?.().catch(()=>{});$('vol').oninput=e=>{if(nativeAudioReady&&nativeAudio)nativeAudio.volume=Number(e.target.value)/100;else if(player?.setVolume)player.setVolume(Number(e.target.value))};$('seek').disabled=true;$('seek').title='Live radio: seeking is locked';
setupNativeAudio();setInterval(tick,1000);tick();startProgress();setInterval(async()=>{try{const r=await fetch('/api/listeners/heartbeat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sessionId:session})}),d=await r.json();$('listeners').textContent=d.listeners||1;$('tuneListeners').textContent=d.listeners||1}catch{}},20000);
(async()=>{await bootstrap();await syncStation(false);startStationSync();loadYTApi()})();
