const PROGRAMS=[];
let songs=[],current=null,player=null,playerReady=false,playing=false,localPaused=false,ytApiFailed=false,stationState=null,stationPoll=null,progressTimer=null,serverClockOffsetMs=0,nativeAudio=null,nativeAudioReady=false,deferredInstall=null;
const RADIO_SYNC_MS=1500,RADIO_DRIFT_SEC=.75,session=localStorage.getItem('zubeen_sid')||crypto.randomUUID();
localStorage.setItem('zubeen_sid',session);const $=id=>document.getElementById(id);
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function fmt(sec){sec=Math.max(0,Math.floor(Number(sec)||0));return`${Math.floor(sec/60)}:${String(sec%60).padStart(2,'0')}`}
function mins(t){const [h,m]=String(t||'00:00').split(':').map(Number);return(h||0)*60+(m||0)}
function now(){const d=new Date(),m=d.getHours()*60+d.getMinutes();const p=PROGRAMS.find(x=>{const s=mins(x.start),e=mins(x.end);return s<e?m>=s&&m<e:m>=s||m<e})||PROGRAMS[PROGRAMS.length-1];return{d,m,p}}
function stationPosition(st){if(!st)return 0;if(st.startedAt)return Math.max(0,(Date.now()+serverClockOffsetMs-Number(st.startedAt))/1000);return Math.max(0,Number(st.position)||0)}
function notice(t,ok=false){if(!$('notice'))return;$('notice').textContent=t;$('notice').className='notice '+(ok?'ok':'')}
function tick(){const x=now(),d=x.d,clock=d.toLocaleTimeString('en-IN',{hour:'numeric',minute:'2-digit'}),date=d.toLocaleDateString('en-IN',{weekday:'long',day:'2-digit',month:'long',year:'numeric'});for(const id of ['clock','bigClock','tuneClock'])if($(id))$(id).textContent=clock;if($('date'))$('date').textContent=`${date} · IST`;if($('bigDate'))$('bigDate').textContent=date;if($('tuneDate'))$('tuneDate').textContent=`${date} · IST`;if(x.p){if($('programName'))$('programName').textContent=x.p.name.toUpperCase();if($('currentShow'))$('currentShow').textContent=x.p.name;if($('tuneProgram'))$('tuneProgram').textContent=x.p.name.toUpperCase();const end=mins(x.p.end),left=end> x.m?end-x.m:1440-x.m+end;if($('programRemain'))$('programRemain').textContent=`${left} MIN LEFT`;const idx=PROGRAMS.indexOf(x.p);if($('nextShow'))$('nextShow').textContent=PROGRAMS[(idx+1)%PROGRAMS.length]?.name||'—'}}
function updateProgress(){try{let t=stationPosition(stationState),d=Number(stationState?.duration||current?.duration||0);if(nativeAudioReady&&nativeAudio){t=Number(nativeAudio.currentTime||0);d=Number(nativeAudio.duration||d)}else if(playerReady&&player&&typeof player.getCurrentTime==='function'){t=Number(player.getCurrentTime()||0);d=Number(player.getDuration()||d)}if($('cur'))$('cur').textContent=fmt(t);if($('dur'))$('dur').textContent=fmt(d);if($('seek')&&d>0){$('seek').max=String(d);$('seek').value=String(Math.min(t,d))}}catch{}}
function startProgress(){clearInterval(progressTimer);progressTimer=setInterval(updateProgress,200)}
async function loadPrograms(){try{const r=await fetch('/api/schedule',{cache:'no-store'}),d=await r.json();PROGRAMS.splice(0,PROGRAMS.length,...(d.items||[]));tick()}catch{PROGRAMS.splice(0,PROGRAMS.length,{name:'Zubeen Radio',start:'00:00',end:'00:00',enabled:true})}}
async function bootstrap(){const category=now().p?.name;notice('Automatic song catalogue loading…');try{const r=await fetch('/api/radio/bootstrap',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({category})}),d=await r.json();if(!r.ok)throw new Error(d.error||'Radio server error');songs=(d.items||[]).filter(s=>s.youtubeId||s.audioUrl);notice(d.api?'YouTube automatic discovery active.':'Radio ready — catalogue active.',true)}catch(e){notice(e.message||'Radio load failed')}}
function setMediaSession(song){try{if(!('mediaSession'in navigator))return;navigator.mediaSession.metadata=new MediaMetadata({title:song?.title||'Zubeen Radio',artist:song?.artist||'Zubeen Garg',album:'Zubeen Radio',artwork:song?.thumbnail?[{src:song.thumbnail,sizes:'512x512',type:'image/jpeg'}]:[]});navigator.mediaSession.setActionHandler('play',resumeLocal);navigator.mediaSession.setActionHandler('pause',pauseLocal);navigator.mediaSession.setActionHandler('seekbackward',e=>seekNative(-(e.seekOffset||10)));navigator.mediaSession.setActionHandler('seekforward',e=>seekNative(e.seekOffset||10))}catch{}}
function seekNative(delta){if(nativeAudioReady&&nativeAudio){nativeAudio.currentTime=Math.max(0,Math.min(nativeAudio.duration||Infinity,nativeAudio.currentTime+delta));updateProgress()}}
function setupNativeAudio(){nativeAudio=$('radioAudio');if(!nativeAudio)return;nativeAudio.addEventListener('playing',()=>{nativeAudioReady=true;playing=true;$('wave')?.classList.add('live');setPlayLabel()});nativeAudio.addEventListener('pause',()=>{playing=false;$('wave')?.classList.remove('live');setPlayLabel()});nativeAudio.addEventListener('ended',()=>{playing=false;localPaused=false;setPlayLabel();setTimeout(()=>syncStation(false),250)});nativeAudio.addEventListener('error',()=>{nativeAudioReady=false;notice('Direct audio source could not be played. Falling back to YouTube.',false);if(current?.youtubeId)playYoutube(current,stationPosition(stationState),!localPaused)});nativeAudio.addEventListener('loadedmetadata',()=>{nativeAudioReady=true})}
function playNative(song,position,autoPlay){if(!nativeAudio||!song.audioUrl)return false;nativeAudioReady=false;nativeAudio.src=song.audioUrl;try{nativeAudio.currentTime=Math.max(0,Number(position)||0)}catch{}setMediaSession(song);if(autoPlay)nativeAudio.play().catch(()=>notice('Tap TUNE IN once to allow background audio.'));return true}
function playYoutube(song,position,autoPlay){if(playerReady&&player&&song.youtubeId){player.loadVideoById({videoId:song.youtubeId,startSeconds:Math.max(0,position||0)});autoPlay?player.playVideo():player.pauseVideo();setMediaSession(song);return}if(ytApiFailed||!window.YT)showDirectEmbed(song.youtubeId,autoPlay,position);setMediaSession(song)}
function showDirectEmbed(id,autoplay=false,startSeconds=0){const box=$('yt');if(!id||!box)return;const src=`https://www.youtube.com/embed/${encodeURIComponent(id)}?autoplay=${autoplay?1:0}&start=${Math.floor(Math.max(0,startSeconds))}&controls=0&enablejsapi=1&rel=0&playsinline=1&modestbranding=1&origin=${encodeURIComponent(location.origin)}`;box.innerHTML=`<iframe id="ytDirect" title="Zubeen Radio YouTube Player" src="${src}" allow="autoplay; encrypted-media; picture-in-picture" allowfullscreen></iframe>`;playerReady=false;playing=autoplay;localPaused=false;setPlayLabel()}
function applySong(song,position=0,autoPlay=false){if(!song)return;current=song;if($('title'))$('title').textContent=current.title;if($('artist'))$('artist').textContent=current.artist||'Zubeen Garg';if($('meta'))$('meta').textContent=`${current.year||'—'} • ${current.audioUrl?'Direct audio stream':current.source==='youtube-api'?'YouTube API':'YouTube'} • GLOBAL RADIO`;if($('cover')){$('cover').style.backgroundImage=current.thumbnail?`url("${current.thumbnail}")`:'';$('cover').classList.toggle('has',!!current.thumbnail);$('cover').textContent=current.thumbnail?'':'ZG'}if(current.audioUrl){if(playNative(current,position,autoPlay))return}playYoutube(current,position,autoPlay)}
function applyStationState(st,autoPlay=false){if(!st?.song)return;if(st.serverNow)serverClockOffsetMs=Number(st.serverNow)-Date.now();const target=stationPosition(st),same=current?.id===st.song.id;stationState=st;if(!same){applySong(st.song,target,autoPlay);return}if(nativeAudioReady&&nativeAudio){try{if(Math.abs(nativeAudio.currentTime-target)>RADIO_DRIFT_SEC)nativeAudio.currentTime=target;if(autoPlay&&!localPaused)nativeAudio.play().catch(()=>{})}catch{}}else if(playerReady&&player){try{const cur=Number(player.getCurrentTime()||0);if(Math.abs(cur-target)>RADIO_DRIFT_SEC)player.seekTo(target,true);if(autoPlay&&!localPaused)player.playVideo()}catch{}}}
async function syncStation(autoPlay=false){const category=now().p?.name;try{const r=await fetch('/api/radio/state?category='+encodeURIComponent(category),{cache:'no-store'}),st=await r.json();if(!r.ok)throw new Error(st.error||'Station state unavailable');applyStationState(st,autoPlay)}catch(e){if(!stationState&&songs[0])applySong(songs[0],0,autoPlay)}}
function startStationSync(){clearInterval(stationPoll);stationPoll=setInterval(()=>syncStation(false),RADIO_SYNC_MS)}
async function syncAndPlay(){try{const r=await fetch('/api/radio/state?category='+encodeURIComponent(now().p.name),{cache:'no-store'}),st=await r.json();if(!r.ok)throw new Error(st.error||'Station unavailable');applyStationState(st,true);notice('Live radio • synchronized with the station.',true);$('tune')?.classList.add('hide')}catch(e){notice(e.message||'Radio connection unavailable.')}}
function onYTReady(){try{player=new YT.Player('yt',{width:'100%',height:'100%',videoId:'',playerVars:{controls:0,rel:0,playsinline:1,origin:location.origin},events:{onReady:()=>{playerReady=true;if(current?.youtubeId)player.cueVideoById({videoId:current.youtubeId,startSeconds:stationPosition(stationState)});try{const d=player.getDuration();if(d>0)reportDuration(d)}catch{}},onStateChange:e=>{if(e.data===YT.PlayerState.PLAYING){playing=true;$('wave')?.classList.add('live');setPlayLabel();try{if(player.getDuration()>0)reportDuration(player.getDuration())}catch{}}else if(e.data===YT.PlayerState.PAUSED||e.data===YT.PlayerState.CUED){playing=false;$('wave')?.classList.remove('live');setPlayLabel()}else if(e.data===YT.PlayerState.ENDED){playing=false;localPaused=false;setPlayLabel();setTimeout(()=>syncStation(false),300)}},onError:e=>{playing=false;setPlayLabel();notice(`YouTube playback error ${e.data}; station will continue.`,false);setTimeout(()=>syncStation(false),500)}}})}catch{ytApiFailed=true;if(current?.youtubeId)showDirectEmbed(current.youtubeId,false)}}
window.onYouTubeIframeAPIReady=onYTReady;
function loadYTApi(){if(window.YT?.Player){onYTReady();return}const s=document.createElement('script');s.src='https://www.youtube.com/iframe_api';s.async=true;s.onerror=()=>{ytApiFailed=true;notice('YouTube API unavailable.',false)};document.head.appendChild(s);setTimeout(()=>{if(!playerReady&&!window.YT?.Player){ytApiFailed=true;if(current?.youtubeId)showDirectEmbed(current.youtubeId,false)}},7000)}
function setPlayLabel(){if($('play'))$('play').textContent=localPaused?'▶ RESUME':playing?'❚❚ PAUSE':'▶ TUNE IN'}
function sendYTCommand(func,args=[]){const frame=document.getElementById('ytDirect');if(frame)try{frame.contentWindow.postMessage(JSON.stringify({event:'command',func,args}),'https://www.youtube.com')}catch{}}
function pauseLocal(){localPaused=true;playing=false;if(nativeAudioReady&&nativeAudio)nativeAudio.pause();else if(playerReady&&player?.pauseVideo)player.pauseVideo();else sendYTCommand('pauseVideo');$('wave')?.classList.remove('live');setPlayLabel();notice('Paused for this listener • station continues for everyone else.',true)}
function resumeLocal(){localPaused=false;if(nativeAudioReady&&nativeAudio)nativeAudio.play().catch(()=>notice('Tap the player once to resume audio.'));else if(playerReady&&player?.playVideo)player.playVideo();else sendYTCommand('playVideo');playing=true;$('wave')?.classList.add('live');setPlayLabel()}
async function reportDuration(duration){if(!current?.id||!duration)return;try{const r=await fetch('/api/radio/report-duration',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({category:now().p.name,songId:current.id,duration})});if(r.ok)stationState=await r.json()}catch{}}
function installPWA(){if(deferredInstall){deferredInstall.prompt();deferredInstall.userChoice.finally(()=>{deferredInstall=null})}else notice('Browser menu → Install Zubeen Radio / Add to Home Screen.',true)}
$('tuneBtn')?.addEventListener('click',syncAndPlay);$('play')?.addEventListener('click',()=>localPaused?resumeLocal():playing?pauseLocal():syncAndPlay());$('bgBtn')?.addEventListener('click',()=>document.body.classList.toggle('no-bg'));$('screenBtn')?.addEventListener('click',()=>document.documentElement.requestFullscreen?.().catch(()=>{}));$('installBtn')?.addEventListener('click',installPWA);$('vol')?.addEventListener('input',e=>{if(nativeAudioReady&&nativeAudio)nativeAudio.volume=Number(e.target.value)/100;else if(player?.setVolume)player.setVolume(Number(e.target.value))});if($('seek')){$('seek').disabled=true;$('seek').title='Live radio: seeking is locked'}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;$('installBtn')?.classList.remove('hide')});
setupNativeAudio();setInterval(tick,1000);tick();startProgress();setInterval(async()=>{try{const r=await fetch('/api/listeners/heartbeat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sessionId:session})}),d=await r.json();if($('listeners'))$('listeners').textContent=d.listeners||1;if($('tuneListeners'))$('tuneListeners').textContent=d.listeners||1}catch{}},20000);
(async()=>{await loadPrograms();await bootstrap();await syncStation(false);startStationSync();loadYTApi()})();
